export const wishes = [
  {
    id: '3f1a8b2',
    count: 34,
    category: 'ورش وتعلّم',
    title: 'ورش مسائية بعد الشغل',
    description: 'أغلب الورش الصبح ومعظمنا شغال — نفسنا بمواعيد ٦ أو ٧ مساءً.',
    endorsers: ['ن', 'ك', 'ه', 'م'],
    endorsersText: 'نادية، كمال، هالة، محمود +٣٠',
    isEndorsed: true,
  },
  {
    id: '7c2d4e1',
    count: 27,
    category: 'ورش وتعلّم',
    title: 'كورس تصوير بالموبايل للمبتدئين',
    description: 'مش كلنا معانا كاميرات — نفسنا نتعلم نصوّر كويس باللي في إيدينا.',
    endorsers: ['ه', 'ك', 'ن'],
    endorsersText: 'هالة، كمال، نادية +٢٤',
    isEndorsed: false,
  },
  {
    id: 'a9b5c3d',
    count: 19,
    category: 'مساحات',
    title: 'مساحة عمل مشتركة بالشهامة',
    description: 'مكان هادي بإنترنت وكهربا نشتغل منه بالساعة — من غير فلوس.',
    endorsers: ['م', 'س', 'ك'],
    endorsersText: 'محمود، سارة، كمال +١٦',
    isEndorsed: false,
  },
  {
    id: 'e4f6a7b',
    count: 12,
    category: 'فعاليات',
    title: 'ليالي حكي في الأحياء البعيدة',
    description: 'أغلب الفعاليات في وسط البلد — نفسنا تيجي عندنا في حلوان وشبرا.',
    endorsers: ['ن', 'ه'],
    endorsersText: 'نادية، هالة +١٠',
    isEndorsed: false,
  },
  {
    id: '8d1c2e3',
    count: 8,
    category: 'خدمات',
    title: 'استشارات قانونية للفنانين المستقلين',
    description: 'عقود العمل الحر وحقوق الملكية — محتاجين حد يبسّطها لنا.',
    endorsers: ['ك', 'س'],
    endorsersText: 'كمال، سارة +٦',
    isEndorsed: false,
  },
]

export const filterButtons = [
  { id: 'sort', labelKey: 'filter.mostEndorsed' },
  { id: 'latest', labelKey: 'filter.latest' },
  { id: 'workshop', labelKey: 'filter.workshopLearning' },
  { id: 'events', labelKey: 'filter.events' },
  { id: 'services', labelKey: 'filter.services' },
  { id: 'spaces', labelKey: 'filter.spaces' },
]
